### 1. Extract Folder Topic Names

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import os
import re

In [2]:
dataset_dir = Path('./20_newsgroups')
topic_names = sorted([topic.name for topic in dataset_dir.iterdir() if topic.is_dir()])
print(f"Number of topics: {len(topic_names)}")

Number of topics: 20

### 2. Data Loading Pipeline

In [3]:
def clean_newsgroup_body(raw_text):
    parts = raw_text.split('\n\n', 1) # headers from body
    body = parts[1] if len(parts) > 1 else raw_text
    text = body.lower()
    text = re.sub(r'^\s*[|>#]{2,}\s*$', '', text, flags=re.MULTILINE) # remove lines starting with >, |, # (common in quoted text)
    text = re.sub(r'(^|\n)\s*>[^\n]*', '', text) # remove quoted text, > & spaces
    text = re.sub(r'[^a-z\s]', ' ', text) # remove non-alphabetic characters, keep spaces
    text = re.sub(r'\s+', ' ', text).strip() # remove extra spaces and newlines, replace with single space
    text = re.sub(r'\S*@\S*\s?', '', text) # remove email addresses
    text = re.sub(r'\s+', ' ', text).strip() # removes white spaces and newlines, replaces with single space
    return text

In [4]:
def load_dataset_to_dataframe(folder_path):
    data_records = []
    
    for label_dir in os.listdir(folder_path): # iterate through root newsgroup folders
        dir_path = os.path.join(folder_path, label_dir)
        
        if not os.path.isdir(dir_path): # skipping non-directory files if any
            continue
            
        for file_name in os.listdir(dir_path): # iterate through files in each category folder
            file_path = os.path.join(dir_path, file_name)
            try:
                with open(file_path, "r", encoding="latin-1") as f: # read and use latin-1 encoding to prevent UnicodeDecodeErrors
                    raw_content = f.read()
                    cleaned_text = clean_newsgroup_body(raw_content) # clean the text using the defined function
                    if cleaned_text:
                        data_records.append({"file_id": file_name, "label": label_dir, 
                        "text": cleaned_text, "original_length": len(raw_content)}) # append only cleaned text
            except Exception as e:
                print(f"Failed to read {file_path}: {e}")
                
    return pd.DataFrame(data_records) # convert dict list of records to a DataFrame

In [5]:
dataset_path = "./20_newsgroups" 
df = load_dataset_to_dataframe(dataset_path)

print(f"Successfully loaded {len(df)} documents.")
print("\nClass Distribution:")
print(df['label'].value_counts())

Successfully loaded 19955 documents.

Class Distribution:
label
talk.politics.guns          1000
talk.politics.mideast       1000
talk.politics.misc          1000
talk.religion.misc          1000
alt.atheism                  999
rec.sport.baseball           999
rec.sport.hockey             999
sci.crypt                    999
sci.electronics              999
sci.space                    999
comp.windows.x               998
rec.autos                    998
sci.med                      998
comp.graphics                997
comp.sys.ibm.pc.hardware     997
rec.motorcycles              997
soc.religion.christian       997
comp.sys.mac.hardware        996
comp.os.ms-windows.misc      992
misc.forsale                 991
Name: count, dtype: int64

In [6]:
df.shape

(19955, 4)

In [7]:
df.head()

,file_id,label,text,original_length
0,49960,alt.atheism,archive name atheism resources alt atheism arc...,12425
1,51060,alt.atheism,archive name atheism introduction alt atheism ...,32531
2,51119,alt.atheism,in article mimsy umd edu mangoe cs umd edu cha...,4550
3,51120,alt.atheism,dmn kepler unh edu until kings become philosop...,2067
4,51121,alt.atheism,in article n hy apr harder ccr p ida org n hy ...,1347

In [8]:
random_texts = df['text'].sample(n=10)

for i, text in enumerate(random_texts, 1):
    print(f"{i}) - RANDOM DOCUMENT")
    print(text + "...\n")

1) - RANDOM DOCUMENT
in article schinder leprss gsfc nasa gov paul j schinder schinder leprss gsfc nasa gov wrote when you look into the math of the different possible frames of reference you will find out that this time is not physically relevant the relevant time for the falling object center of the hole where the evil singularity lurks there is no singularity at the horizon the appearance that there is one comes from attempting to use a coordinate system that doesn t map properly physically in this geometry rather analogous to the singularity at the north and south poles of the earth when using latitude and longitude lines such singular behavior as the earlier post suggested infinite time to reach the horizon is a mathematical artifact of the wrong choice of coordinates as paul says in the object s frame of reference it will hit the horizon in finite time and then plunge to the singularity that is a real singularity in a short for small holes further finite amount of time not only that but to an outside observer an object that falls into a black hole disappears in a finite time also in spite of the relativistic slow down that intuition suggests this is because any light emitted by the object as it falls or is shone onto it by a separate flashlight consists of individual finite quanta and only a finite number of these can reach the object before it plunges through the horizon these will be succesively more red shifted true but only a finite number of them will hit the object and following ones will be too late to interact with the object until they too are inside the horizon and thus cannot come out this reddening dimming and disappearance is exponentially fast as the object approaches the horizon when you do the math as paul says this is discussed in misner thorne and wheeler s book gravity where they talk about the appropriatness sp of the term black hole and the inappropriatness sp of an older term frozen star which was used earlier in this century before all the implications of black hole theory were understood do not let the math deter you from looking at this book it s got a lot of good prose discussions of this material in between the equations that is very good reading imho of course it s all just theory gene battin battin cyclops iucf indiana edu no sig yet...

2) - RANDOM DOCUMENT
to the best of my knowledge there aren t any problems with quadras and blind transfers trouble with blind transfers usually means the programmer screwed up the tibs or didn t test their driver with the device in question well designed tibs poll or loop at every point where delays of sec occur this usually occurs at the first byte of each block of a transfer but some devices can hiccup in the middle of blocks if this happens in the middle of a blind transfer there is the possibility of losing or gaining a byte depending on which direction the tranfer was going in anycase the scsi manager will eventually return a phase error at the end of the transaction because it is out of sync actual data loss would only occur if the driver didn t pay attention to the errors coming back note that this effect is not caused by anything actually on the scsi bus but rather by the transfer loops inside the scsi manager the problem occurs when the processor bus errors trying to access the scsi chip when the next byte hasn t been clocked yet also note that the bus error is dealt with by a bus error handler and doesn t crash the machine clinton bauder apple computer...

3) - RANDOM DOCUMENT
hello i have the following for sale most of the books are in perfect condition if interested please e mail to chungy rpi edu through the telescope hard cover surface physics soft cover the physics of structurally disordered matter an introduction soft cover subatomic physics hard cover a first general relativity hard cover non equilibrium thermodynamics soft cover advances in atomic and molecular physics vol hard cover advances in atomic and molecular physics vol hard cover molecular beams hard cover molecular beams and reaction kinetics hard cover perturbation methods in applied mathematics hard cover elementary differential equations and boundary value problems hard cover vector mechanics for engineers statics and dynamics hard cover free electron lasers hard cover physical mechanics hard cover...

4) - RANDOM DOCUMENT
in article apr skcla monsanto com mpmena skcla monsanto com writes let s see how the weather is saturday or sunday it sucks today what time is good you re welcome to give any of the ones i have a try as for the gargoyles if you want mine you can have em i think the bridge of my nose holds them too far from my face same deal for the two of my friends who tried them for people who use them with a full face helmet all bets are off sorry if they fit you well and took my complaint personally yes the oakleys are much more desirable squid attire also the gargoyles aren t that ugly even in my opinion or i wouldn t have tried them michael manning mmanning icomsim com nextmail accepted flstf fatboy ducati ss...

5) - RANDOM DOCUMENT
in article apr isc br isc br com steveh thor isc br com steve hendricks writes steve you re the one who suggested that a failed government should be an ideal proving ground i never felt that way in the first place quite the contrary i think a better proving ground would be someplace that already had a governemnt that would prevent outright acts of agression yet had a strong spirit of individualism and initiative someplace like texas mr grinch and while texas taxpayers might willingly eliminate tax support for ut and tamu i m not sure they d support gutting the football programs football can pay for itself then there s the impact on ross perot s fortune of eliminating the various why he s already made it sure nodoby else will be able to bilk the public in the same specific ways but why should he or i care all in all texas doesn t seem to be a very likely place for libertarianism to take hold more likely than most places when i was there the most important state issue was whether to have a state income tax or instead legalize a popular vice for fund raising and vice won a decisive victory mr grinch p s now that he s safely dead i expect david koresh to become the hero of popular folk ballads and the atf to be generally equated with santa anna...

6) - RANDOM DOCUMENT
scott prism gatech edu scott holt writes that is an assumption on your part where is your proof that one always will degenerate into hating the sinner because he hates the sin i am reminded of the civil rights movement in america it is true that many individuals hated the proponents of racism it is also true that many individuals hated segregation and discrimination with their whole heart and never degenerated into hating the individuals who practiced it dr king s message was this love the individual the loving of the individual would transform him into a friend however this did not take away his hatred for segregation his hatred for injustice i would ask did john the baptist practice love when he criticized the jewish leaders of his day did jesus practice love when he threw the moneychangers out of the temple we must have at least a distase for sin we must in order to fight it in ourselves also we must be ready for the call from god to call sin by its right name jesus loved everyone but he called sin by its right name it is true that love for others is to guide every step of our walk but it is also true that sometimes the love for god calls us to stand up for truth competition is the law of the jungle cooperation is the law of civilization eldridge cleaver sherman cox ii scox uahcs cs uah edu...

7) - RANDOM DOCUMENT
in article c pua k u mailer cc fsu edu dlecoint garnet acns fsu edu darius lecointe writes make that where did i see that poll recently about the very religious and adultery was it this newsgroup or alt atheism or some other place dean kaflowitz...

8) - RANDOM DOCUMENT
okay mr dyer we re properly impressed with your philosophical skills and ability to insult people you re a wonderful speaker and an adept politician however i believe that all you were asked to do was simply provide scientific research refuting the work of olney i don t think the original poster sought to start a philisophical debate she wanted some information given a little effort one could justify that shooting oneself with a before breakfast is a healthy practice but we re not particularily interested in what you can verbally prove disprove or rationalize where s the research where are the studies i appoligize if this sounds flamish i simply would like to see the thread get back on track lone wolf happy are they who dream dreams ed philips and pay the price to see them come true slyx cc usu edu unknown...

9) - RANDOM DOCUMENT
in c l tg k q news cso uiuc edu cobb alexia lis uiuc edu writes ah but what exactly is inherently abhorrent and why is it so what you re saying is in effect i think some things are repulsive and i know a whole bunch of other people who agree with me so they should be deemed absolutely immoral now and forever period which in and of itself is nice enough to some extent i agree with you but i do not agree that things are inherently or absolutely immoral they are labeled immoral each for its own good reason and if the reason can even theoretically change then so can the label no it doesn t humans are to some extent similar because we all belong to the same species that that species has evolved is another story altogether to a certain extent evolution can even lend credence to moral absolutism of a flavour you re saying morality is what ll keep society alive and kicking it is i think up to a point but societies are not all alike and neither are their moralities similar identical no it s falsifiable through finding someoe who was created different whatever that might be in the real world disclaimer it s great to be young and insane...

10) - RANDOM DOCUMENT
in article vice ico tek com bobbe vice ico tek com robert beauchaine writes well again i am doing as much as the poster i was replying too i am quite busy and really don t have the time to respond in full scholarly form to every accusation that is flippantly made by someone who s being clearly antagonistic i have considered it but if someone spreads falsehoods out of ignorance then they are still spreading falsehoods those falsehoods generally do not come out of nowhere but are produced by people who know that what they are saying is at least not the whole truth i still consider such spreading of falsehoods propaganda on some level bob i never accused you of having your head up your ass it takes me quite some time in dealing with someone before accusing them of having their head up their ass i was accusing the original poster benedikt i believe of being so impaired cheers gregg...

### 3. Text Pre-Processing Stage

In [9]:
import nltk
import ssl
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from tqdm import tqdm

In [10]:
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt_tab')       # tokenizer
nltk.download('stopwords')   # stop words list
nltk.download('wordnet')     # lemmatization dictionary
nltk.download('omw-1.4')     # open multilingual wordnet (required by newer NLTK versions)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\manoj\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\manoj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\manoj\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\manoj\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [11]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [12]:
custom_stop_words = {'write', 'article', 'post', 'know', 'like', 'just', 'say', 'think', 'use', 'make', 'good', 'time', 'people'}
stop_words.update(custom_stop_words)

In [13]:
def nltk_process_text(text):
    tokens = word_tokenize(text) # tokenize the text (splits string into list of words)
    cleaned_tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words and len(word) > 2]
    return " ".join(cleaned_tokens)

In [14]:
tqdm.pandas(desc="NLTK Tokenizing, Lemmatizing & Stop Word Removal")

print("Starting NLTK pre-processing...")
df['processed_text'] = df['text'].progress_apply(nltk_process_text)

print("Pre-processing complete! Check the first few rows:")
display(df[['label', 'processed_text']].head())

Starting NLTK pre-processing...

NLTK Tokenizing, Lemmatizing & Stop Word Removal: 100%|██████████| 19955/19955 [00:15<00:00, 1315.54it/s]

Pre-processing complete! Check the first few rows:

         label                                     processed_text
0  alt.atheism  archive name atheism resource alt atheism arch...
1  alt.atheism  archive name atheism introduction alt atheism ...
2  alt.atheism  mimsy umd edu mangoe umd edu charley wingate w...
3  alt.atheism  dmn kepler unh edu king become philosopher phi...
4  alt.atheism  apr harder ccr ida org harder ccr ida org bob ...

In [15]:
df[['file_id', 'original_length', 'text', 'processed_text', 'label']].head()

,file_id,original_length,text,processed_text,label
0,49960,12425,archive name atheism resources alt atheism arc...,archive name atheism resource alt atheism arch...,alt.atheism
1,51060,32531,archive name atheism introduction alt atheism ...,archive name atheism introduction alt atheism ...,alt.atheism
2,51119,4550,in article mimsy umd edu mangoe cs umd edu cha...,mimsy umd edu mangoe umd edu charley wingate w...,alt.atheism
3,51120,2067,dmn kepler unh edu until kings become philosop...,dmn kepler unh edu king become philosopher phi...,alt.atheism
4,51121,1347,in article n hy apr harder ccr p ida org n hy ...,apr harder ccr ida org harder ccr ida org bob ...,alt.atheism

In [16]:
output_dir = "./data"
output_file = os.path.join(output_dir, "processed_newsgroups.csv")

os.makedirs(output_dir, exist_ok=True)

print(f"Saving processed data to {output_file}...")
df[['file_id', 'original_length', 'text', 'processed_text', 'label']].to_csv(output_file, index=False) 
print("Save complete! Your intermediate data is safely stored.")

Saving processed data to ./data\processed_newsgroups.csv...
Save complete! Your intermediate data is safely stored.