### 1. Extract Folder Topic Names

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import os
import re

In [2]:
dataset_dir = Path('./20_newsgroups')
topic_names = sorted([topic.name for topic in dataset_dir.iterdir() if topic.is_dir()])
print(f"Number of topics: {len(topic_names)}")

Number of topics: 20

### 2. Data Loading Pipeline

In [3]:
def clean_newsgroup_body(raw_text):
    parts = raw_text.split('\n\n', 1) # headers from body
    body = parts[1] if len(parts) > 1 else raw_text
    text = body.lower()
    text = re.sub(r'^\s*[|>#]{2,}\s*$', '', text, flags=re.MULTILINE) # remove lines starting with >, |, # (common in quoted text)
    text = re.sub(r'(^|\n)\s*>[^\n]*', '', text) # remove quoted text, > & spaces
    text = re.sub(r'[^a-z\s]', ' ', text) # remove non-alphabetic characters, keep spaces
    text = re.sub(r'\s+', ' ', text).strip() # remove extra spaces and newlines, replace with single space
    text = re.sub(r'\S*@\S*\s?', '', text) # remove email addresses
    text = re.sub(r'\s+', ' ', text).strip() # removes white spaces and newlines, replaces with single space
    return text

In [4]:
def load_dataset_to_dataframe(folder_path):
    data_records = []
    
    for label_dir in os.listdir(folder_path): # iterate through root newsgroup folders
        dir_path = os.path.join(folder_path, label_dir)
        
        if not os.path.isdir(dir_path): # skipping non-directory files if any
            continue
            
        for file_name in os.listdir(dir_path): # iterate through files in each category folder
            file_path = os.path.join(dir_path, file_name)
            try:
                with open(file_path, "r", encoding="latin-1") as f: # read and use latin-1 encoding to prevent UnicodeDecodeErrors
                    raw_content = f.read()
                    cleaned_text = clean_newsgroup_body(raw_content) # clean the text using the defined function
                    if cleaned_text:
                        data_records.append({"file_id": file_name, "label": label_dir, 
                        "text": cleaned_text, "original_length": len(raw_content)}) # append only cleaned text
            except Exception as e:
                print(f"Failed to read {file_path}: {e}")
                
    return pd.DataFrame(data_records) # convert dict list of records to a DataFrame

In [5]:
dataset_path = "./20_newsgroups" 
df = load_dataset_to_dataframe(dataset_path)

print(f"Successfully loaded {len(df)} documents.")
print("\nClass Distribution:")
print(df['label'].value_counts())

Successfully loaded 19955 documents.

Class Distribution:
label
talk.politics.mideast       1000
talk.politics.misc          1000
talk.politics.guns          1000
talk.religion.misc          1000
alt.atheism                  999
rec.sport.baseball           999
rec.sport.hockey             999
sci.crypt                    999
sci.electronics              999
sci.space                    999
rec.autos                    998
sci.med                      998
comp.windows.x               998
rec.motorcycles              997
comp.graphics                997
comp.sys.ibm.pc.hardware     997
soc.religion.christian       997
comp.sys.mac.hardware        996
comp.os.ms-windows.misc      992
misc.forsale                 991
Name: count, dtype: int64

In [6]:
df.shape

(19955, 4)

In [7]:
df.head()

,file_id,label,text,original_length
0,75895,talk.politics.mideast,in article apr ncsu edu hernlem chess ncsu edu...,1744
1,76248,talk.politics.mideast,ab z virginia edu andi beyer writes uh oh the ...,1602
2,76277,talk.politics.mideast,andrew varvel writes ah c mon give the guy thr...,1810
3,76045,talk.politics.mideast,in article apr thunder mcrcim mcgill edu hasan...,2544
4,77197,talk.politics.mideast,srinivas suder writes precisely why not cuba w...,2365

In [8]:
random_texts = df['text'].sample(n=10)

for i, text in enumerate(random_texts, 1):
    print(f"========== RANDOM DOCUMENT {i} ==========")
    print(text + "...\n")

========== RANDOM DOCUMENT 1 ==========
it s my understanding that koresh didn t want to come out alive rather to fulfill his own interpretations of some prophecies more interesting was discussions on the news about subterannean tunnels under the complex wonder if he was planning on hiding out a few days then re emerging resurrected sounds a bit like the book passover plot to me hmmmmm seth rosenthal disclaimer all opinions are my own not my employers...

========== RANDOM DOCUMENT 2 ==========
in article apr aurora alaska edu nsmca aurora alaska edu writes if you re doing large scale satellite servicing being able to do it in a pressurized hangar makes considerable sense the question is whether anyone is going to be doing large scale satellite servicing in the near future to the point of justifying development of such a thing you d almost certainly use air given that you have to pressurize with something safety considerations strongly suggest making it breathable even if the servicing crew is using oxygen masks for normal breathing to avoid needing a ventilation system it s nice if the hangar atmosphere is breathable in a pinch it makes mask functioning much less critical svr resembles a high speed collision henry spencer u of toronto zoology between svr and sunos dick dunn henry zoo toronto edu utzoo henry...

========== RANDOM DOCUMENT 3 ==========
have anyone dealt with hardware that fits before i have seen their ad in both macworld and macuser and decided to try them when i needed a new disk the result was not satisfactory and i was just wondering if i was just an isolated case i like to send a letter to the president of hardware that fits do anyone know the address is it the same address as the one i return the products to mei mei su software engineer email mms ltx tr portal com ltx corporation meisu netcom com disclaimer this is a personnal statement only nothing official...

========== RANDOM DOCUMENT 4 ==========
robert beauchaine bobbe vice ico tek com wrote precisely my position as a newbie i tried the point by point approach to debate with these types it wasted both my time and my lifespan ignoring them is not an option since they don t go away and doing so would leave one with large stretches of complete anonymity in this group bob i ve posted here long enough to see your name a few times but i can t recall any point by point approach to anything you ve contributed but i m old probably senile and i may have just forgotten if you could post an example of your invincible logic it might jog my memory bill...

========== RANDOM DOCUMENT 5 ==========
i need tickets to the cleveland showing of phantom of the opera i will pay face value for tickets in the dollar and lower range preferably a matinee show but any in middle to late may will be bought please leave mail...

========== RANDOM DOCUMENT 6 ==========
in article apr magnus acs ohio state edu alaramor magnus acs ohio state edu aaron c laramore writes there is something terribly wrong however with a culture which condemns attacks and all too often kills any of its members who attempt to get an education my mother is an elementary school teacher and she tells me that she and her african american collegues are frustrated to tears by the fact that any african american child who attempts to do well in school and get an education is accused by his her peers of trying to be white and is beaten bullied and tormented by them it goes beyond each passing grade on a test earning a beating in my mother s school one of the most promising young students who happened to be african american had her throat cut by one of these young thugs nobody who buys into such a culture has any hope of being anything but poor and or a thug and or dead regardless of their color what has to be changed is the culture if that culture can t be changed then those african american kids who are willing to separate from it must be separated from it and the murderous thugs of whatever color otherwise future bright young african american girls who wanted to be doctors will end up dead on the school bus let s face it when it comes to utilities microsoft has mike van pelt performed about as well as a savings and loan these are mvp netcom com the guys remember who put backup and restore not to mvp lsil com mention edlin on your hard disk lincoln spector...

========== RANDOM DOCUMENT 7 ==========
mreamy rock concert net michael g reamy support writes one of the monitors i reviewed for the june issue of windows magazine was the mitsubishi i also reviewed a new nanao the f iw which has just been released last year for the may issue of windows i reviewed several monitors including the nanao t i there s no question that the nanao monitors are the best available this year just as they were last year the difference between my ranking of the best in windows and the ranking in windows sources is due mainly to a difference in the testing criteria and the scoring i used different tests than they did and i scored differently there s nothing wrong with the mitsubishi and it scored very highly in my tests but it was a few points shy of perfect incidentally one of the things everyone should do when they re reading reviews of any product whether it s monitors or mice is to read the criteria and methodology carefully unless you know how the product testing was done and on what the scores are based you can t possibly know what they really mean just seeing that i rank a monitor differently from windows sources is meaningless without knowing how we did the ranking likewise it s impossible to tell whether a monitor will meet your needs unless you know how we did the testing after all some of what we do may not apply to you likewise some of what we do may apply more closely in one review than in another you can t always tell anything from reading the or so words of commentary we write if you don t also understand the scoring wayne rash...

========== RANDOM DOCUMENT 8 ==========
from article r uckinncmf gap caltech edu by wen king cs caltech edu wen king su yes it does come with the maxima gxe engine mated to the maxima se transmission and it has decent power for a minivan also check again aamir qazi aamir qazi qazi csd csd uwm edu why should i care i d rather watch drying paint...

========== RANDOM DOCUMENT 9 ==========
in article apr yuma acns colostate edu holland cs colostate edu douglas craig holland writes ok i heard a lot of talk about the nsa s infamous control over encryption export through the itar here s a question say i develop this great new encryption system and i want to sell my software worldwide the thought police then come in and say this algorithm is a threat to national security you will not be permitted to export it at this point what kind of trouble could i get into if i ignored the itar and sold my program to international customers anyway first of all it s not the thought police it s the export police if you move overseas with your great thoughts in your head write the software there and then sell it the us thought police probably can t do too much about it though you might want to check with your lawyer first however if you write the program here and sell it to furriners you are now an international arms dealer and can get thrown in the clink for many years especially if they decide you d be a good example and cuban drug dealers and fanatic middle eastern terrorists buy your stuff definitions of public domain are different for itar purposes so if you ve got a good enough lawyer who ll do your case for free after they ve confiscated everything you own as evidence you might win but nobody wants to go first since the stakes are quite high pray for peace bill bill stewart wcs anchor att com at t bell labs m holmdel nj no i m from new jersey i only work in cyberspace white house commect line fax...

========== RANDOM DOCUMENT 10 ==========
in article c rrw g w austin ibm com login austin ibm com writes justify all you want extended warranties are a ripoff high profit item for the dealer and you didn t buy yr k you get yr k free so what you bought is yr k and you still have to pay every time you use this great warranty better to put your money in the bank and use it for repairs if when you need it considering that your last car was only years old are you sure you will even keep this new one past it s free warranty period btw typical profit on extended warranties is around that s right only of the money needs to go into the collective pot to pay for any future repairs that the group of extended warranty people collect...

### 3. Text Pre-Processing Stage

In [31]:
import nltk
import ssl
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from tqdm import tqdm

In [32]:
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt_tab')       # tokenizer
nltk.download('stopwords')   # stop words list
nltk.download('wordnet')     # lemmatization dictionary
nltk.download('omw-1.4')     # open multilingual wordnet (required by newer NLTK versions)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/manojith/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/manojith/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/manojith/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/manojith/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [33]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [34]:
custom_stop_words = {'write', 'article', 'post', 'know', 'like', 'just', 'say', 'think', 'use', 'make', 'good', 'time', 'people'}
stop_words.update(custom_stop_words)

In [35]:
def nltk_process_text(text):
    tokens = word_tokenize(text) # tokenize the text (splits string into list of words)
    cleaned_tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words and len(word) > 2]
    return " ".join(cleaned_tokens)

In [36]:
tqdm.pandas(desc="NLTK Tokenizing, Lemmatizing & Stop Word Removal")

print("Starting NLTK pre-processing...")
df['processed_text'] = df['text'].progress_apply(nltk_process_text)

print("Pre-processing complete! Check the first few rows:")
display(df[['label', 'processed_text']].head())

Starting NLTK pre-processing...

NLTK Tokenizing, Lemmatizing & Stop Word Removal: 100%|██████████| 19955/19955 [00:06<00:00, 2854.06it/s]

Pre-processing complete! Check the first few rows:

                   label                                     processed_text
0  talk.politics.mideast  apr ncsu edu hernlem chess ncsu edu brad hernl...
1  talk.politics.mideast  virginia edu andi beyer writes first sign argu...
2  talk.politics.mideast  andrew varvel writes mon give guy three day se...
3  talk.politics.mideast  apr thunder mcrcim mcgill edu hasan mcrcim mcg...
4  talk.politics.mideast  srinivas suder writes precisely cuba hatians r...

In [38]:
df[['file_id', 'original_length', 'text', 'processed_text', 'label']].head()

,file_id,original_length,text,processed_text,label
0,75895,1744,in article apr ncsu edu hernlem chess ncsu edu...,apr ncsu edu hernlem chess ncsu edu brad hernl...,talk.politics.mideast
1,76248,1602,ab z virginia edu andi beyer writes uh oh the ...,virginia edu andi beyer writes first sign argu...,talk.politics.mideast
2,76277,1810,andrew varvel writes ah c mon give the guy thr...,andrew varvel writes mon give guy three day se...,talk.politics.mideast
3,76045,2544,in article apr thunder mcrcim mcgill edu hasan...,apr thunder mcrcim mcgill edu hasan mcrcim mcg...,talk.politics.mideast
4,77197,2365,srinivas suder writes precisely why not cuba w...,srinivas suder writes precisely cuba hatians r...,talk.politics.mideast